{{- if .Values.ingress.enabled -}}
{{- $fullName := include "osm-seed.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "osm-seed.name" . }}
    component: ingress
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    {{- if .Values.web.enabled }}
    - host: web.{{ .Values.domain.domainName }}
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ template "osm-seed.fullname" . }}-web
            servicePort: 80
    {{- end }}

    {{- if .Values.tmApi.enabled }}
    - host: tasking-manager-api.{{ .Values.domain.domainName }}
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ template "osm-seed.fullname" . }}-tasking-manager-api
            servicePort: 80
    {{- end }}

    {{- if .Values.taginfo.enabled }}
    - host: taginfo.{{ .Values.domain.domainName }}
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ template "osm-seed.fullname" . }}-taginfo
            servicePort: 80
    {{- end }}
{{- end }}
