version: '3'
services:
  #=========================================================================
  # OMS-SEED-TILER section
  #=========================================================================
  tiler-db:
    image: osmseed-tiler-db:v1
    build: 
      context: ./images/tiler-db
      dockerfile: Dockerfile
    ports:
      -  "5433:5432"
    volumes:
      - ./postgres-gis-data:/var/lib/postgresql/data
    env_file:
      - ./.env-tiler
  tiler-imposm:
    image: osmseed-tiler-imposm:v1
    build: 
      context: ./images/tiler-imposm
      dockerfile: Dockerfile
    volumes:
      - ./tiler-imposm-data:/mnt/data
    depends_on:
      - tiler-db
    env_file: 
      - ./.env-tiler
    command: >
      /bin/bash -c "
      echo Sleep for a while!;
      sleep 20;
      echo starting imposm!;
      ./start.sh"
  tiler-server:
    image: osmseed-tiler-server:v1
    build: 
      context: ./images/tiler-server
      dockerfile: Dockerfile
    volumes:
      - ./tiler-server-data:/mnt/data
    depends_on:
      - tiler-db
      - tiler-imposm
    ports:
      - "9090:9090"
    command: >
      /bin/bash -c "
      echo Sleep for a while!;
      sleep 100;
      echo Starting tiles server!;
      ./start.sh"
    env_file:
      - ./.env-tiler