version: '2'
services:
  web:
    image: openseed-osm-website:v1
    build:
      context: ./openstreetmap-website
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
  # web-production:
  #   image: openseed-osm-website-production:v1
  #   build:
  #     context: ./openstreetmap-website-production
  #     dockerfile: Dockerfile
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - db
  #   environment:
  #     POSTGRES_HOST: $POSTGRES_HOST
  #     POSTGRES_DB: $POSTGRES_DB
  #     POSTGRES_USER: $POSTGRES_USER
  #     POSTGRES_PASSWORD: $POSTGRES_PASSWORD
  db:
    image: openseed-db:v1
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "5432:5431"
    environment:
      POSTGRES_DB: openstreetmap
  import_osm:
    image: openseed-import_osm:v1
    build: 
      context: ./osmosis
      dockerfile: Dockerfile
    depends_on:
      - web
    environment:
      S3_OSM_PATH: $S3_OSM_PATH
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
