version: '3'
services:
  web:
    image: openseed-osm-website:v1
    build:
      context: ./openstreetmap-website
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file: 
      - ./.env
    depends_on:
      - db
  db:
    image: openseed-db:v1
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    env_file: 
      - ./.env
  import_osm:
    image: openseed-import_osm:v1
    build: 
      context: ./osmosis
      dockerfile: Dockerfile
    depends_on:
      - web
    env_file: 
      - ./.env
  dbbackup:
    image: openseed-dbbackup:v1
    build: 
      context: ./dbbackup
      dockerfile: Dockerfile
    depends_on:
      - web
      - db
    command: >
      /bin/bash -c "
      echo Sleep for a while!;
      sleep 20;
      echo Building backup!;
      ./script.sh"
    env_file: 
      - ./.env