version: '2'
services:
  web-production:
    image: openstreetmap-website-production:v1
    build:
      context: ./openstreetmap-website-production
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: openstreetmap
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    depends_on:
      - db
  db:
    image: openseed-db:v1
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: openstreetmap
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
