apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: osmseed
  replicas: 1
  template:
    metadata:
      labels:
        app: osmseed
    spec:
      containers:
      - name: master
        image: developmentseed/osmseed-db:0.0.1-dev
        # image: openseed-db:v1
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 100Mi
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: postgres 
        - name: POSTGRES_DB
          value: openstreetmap
        - name: POSTGRES_PASSWORD
          value: '1234'
