apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: osmseed
  replicas: 1
  template:
    metadata:
      labels:
        app: osmseed
    spec:
      containers:
      - name: web
        image: developmentseed/osmseed-web:0.0.1-dev
        # image: openseed-osm-website:v1
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below:
          # value: env
        ports:
        - containerPort: 80