apiVersion: v1
kind: Service
metadata:
  name: db # keep this name constant as it is how the "Service" is referred to
  labels:
    app: {{ template "osm-seed.name" . }}
    chart: {{ template "osm-seed.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: 5432
      targetPort: 5432 # FIXME / Q: should this rather be a name?
      # protocol: TCP
      # name: http
  selector:
    app: {{ template "osm-seed.name" . }}
    release: {{ .Release.Name }}
