apiVersion: v1
kind: Service
metadata:
  name: db # FIXME: dont hard-code this, send db_host to services that need it via env vars
  labels:
    app: {{ template "osm-seed.name" . }}
    chart: {{ template "osm-seed.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: 5432
      targetPort: 5432 # FIXME / Q: should this rather be a name?
      # protocol: TCP
      # name: http
  selector:
    app: {{ template "osm-seed.name" . }}
    release: {{ .Release.Name }}
    run: {{ .Release.Name }}-db
