apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "osm-seed.fullname" . }}-id-editor
  labels:
    app: {{ template "osm-seed.name" . }}
    component: id-editor-deployment
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.idEditor.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "osm-seed.name" . }}
      release: {{ .Release.Name }}
      run: {{ .Release.Name }}-id-editor
  template:
    metadata:
      labels:
        app: {{ template "osm-seed.name" . }}
        release: {{ .Release.Name }}
        run: {{ .Release.Name }}-id-editor
    spec:
      containers:
        - name: {{ .Chart.Name }}-id-editor
          image: "{{ .Values.idEditor.image }}:{{ .Values.osmSeedVersion }}"
          command: ['./start.sh']
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          # resources:
          #   requests:
          #     memory: {{ .Values.idEditor.resources.requests.memory }}
          #     cpu: {{ .Values.idEditor.resources.requests.cpu }}
          #   limits:
          #     memory: {{ .Values.idEditor.resources.limits.memory }}
          #     cpu: {{ .Values.idEditor.resources.limits.cpu }}
          env:
            - name: OAUTH_CONSUMER_KEY
              value: {{ .Values.idEditor.env.OAUTH_CONSUMER_KEY }}
            - name: OAUTH_SECRET
              value: {{ .Values.idEditor.env.OAUTH_SECRET }}
            # Set domain name or pod ip
              {{- if .Values.domain.enabled }}
            - name: SERVER_URL
              value: {{ .Values.domain.domainName }}
            - name: SERVER_PROTOCOL
              value : {{ .Values.domain.protocolo }}
              {{- else }}
            - name: SERVER_URL
              value: dns
            - name: SERVER_PROTOCOL
              value : http
              {{- end }}