apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-planet-dump-job
  labels:
    app: {{ template "osm-seed.name" . }}
    component: planet-dump-job
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  schedule: {{ quote .Values.planetDump.schedule }}
  startingDeadlineSeconds: 100
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Release.Name }}-planet-dump-job
            image: {{ .Values.planetDump.image }}:{{ .Values.osmSeedVersion }}
            command: ['./start.sh']
            env:
              - name: POSTGRES_HOST
                value: {{ .Release.Name }}-db
              - name: POSTGRES_DB
                value: {{ .Values.db.env.POSTGRES_DB }}
              - name: POSTGRES_PASSWORD
                value: {{ quote .Values.db.env.POSTGRES_PASSWORD }}
              - name: POSTGRES_USER
                value: {{ .Values.db.env.POSTGRES_USER }}
              # In case cloudProvider=aws
              {{ if eq .Values.cloudProvider "aws" }}
              - name: STORAGE
                value: S3
              - name: AWS_DEFAULT_REGION
                value: {{ .Values.AWS_DEFAULT_REGION }}
              - name: S3_OSM_PATH
                value: {{ .Values.AWS_S3_BUCKET }}
              {{- end }}
              # In case cloudProvider=gcp
              {{ if eq .Values.cloudProvider "gcp" }}
              - name: STORAGE
                value: GS
              - name: GCLOUD_PROJECT
                value: {{ .Values.GCP_GCLOUD_PROJECT }}
              - name: GCLOUD_SERVICE_KEY
                value: {{ .Values.GCP_GCLOUD_SERVICE_KEY }}
              - name: GS_OSM_PATH
                value: {{ .Values.GCP_GS_OSM_PATH }}
              {{- end }}
          restartPolicy: Never
      backoffLimit: 3
