apiVersion: batch/v1beta1
kind: pod # This container should be run just one time, it don't need to be a CronJob
metadata:
  name: {{ .Release.Name }}-populate-apidb
  labels:
    app: {{ template "osm-seed.name" . }}
    component: populate-apidb
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
    containers:
    - name: {{ .Release.Name }}-populate-apidb
      image: {{ .Values.populateApidb.image }}:{{ .Values.osmSeedVersion }}
      command: ['./start.sh']
      env:
        - name: POSTGRES_HOST
          value: {{ .Release.Name }}-db
        - name: POSTGRES_DB
          value: {{ .Values.db.env.POSTGRES_DB }}
        - name: POSTGRES_PASSWORD
          value: {{ quote .Values.db.env.POSTGRES_PASSWORD }}
        - name: POSTGRES_USER
          value: {{ .Values.db.env.POSTGRES_USER }}
        - name: URL_FILE_TO_IMPORT
          value: {{.Values.populateApidb.env.URL_FILE_TO_IMPORT}}
    restartPolicy: Never