{{- if .Values.tilerDb.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-tiler-db
  labels:
    app: {{ template "osm-seed.name" . }}
    component: tiler-db-service
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  # In case cloudProvider=aws
  {{- if eq .Values.cloudProvider "aws" }}
  type: LoadBalancer
  {{- end }}
  
  # In case cloudProvider=gcp
  {{- if eq .Values.cloudProvider "gcp" }}
  type: LoadBalancer
  loadBalancerIP : {{ .Values.tilerServer.staticIp }}
  {{- end }}

  # In case cloudProvider=minikube
  {{- if eq .Values.cloudProvider "minikube" }}
  type: NodePort
  {{- end }}
  
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: {{ template "osm-seed.name" . }}
    release: {{ .Release.Name }}
    run: {{ .Release.Name }}-tiler-db
{{- end }}