{{- if .Values.db.enabled -}}
{{- if .Values.db.persistenceDisk.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-pv
  labels:
    app: {{ template "osm-seed.name" . }}
    component: db-pd
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  ############## Minikube ##############
  {{- if eq .Values.cloudProvider "minikube" }}
  storageClassName: local-storage
  capacity:
    storage: {{ .Values.db.persistenceDisk.localVolumeSize }}
  hostPath:
    path: {{ .Values.db.persistenceDisk.localVolumeHostPath | quote }}
  {{- end }}

  ############## AWS Provider ##############
  {{- if eq .Values.cloudProvider "aws" }}
  storageClassName: ""
  capacity:
    storage: {{ .Values.db.persistenceDisk.AWS_ElasticBlockStore_size }}
  awsElasticBlockStore:
    volumeID: {{ .Values.db.persistenceDisk.AWS_ElasticBlockStore_volumeID }}
    fsType: ext4
  {{- end }}

  ############## GCP Provider ##############
  {{- if eq .Values.cloudProvider "gcp" }}
  storageClassName: ""
  capacity:
    storage: {{ .Values.db.persistenceDisk.GCP_gcePersistentDisk_size }}
  gcePersistentDisk:
    pdName: {{ .Values.db.persistenceDisk.GCP_gcePersistentDisk_pdName }}
    fsType: ext4
  {{- end }}

  ############## Azure Provider ##############
  {{- if eq .Values.cloudProvider "azure" }}
  storageClassName: ""
  capacity:
    storage: {{ .Values.db.persistenceDisk.AZURE_PersistentDisk_size }}
  persistentVolumeReclaimPolicy: Retain
  # claimRef:
  #   name: {{ .Release.Name }}-pv-claim
  #   namespace: default
  csi:
    driver: disk.csi.azure.com
    readOnly: false
    volumeHandle: {{ .Values.db.persistenceDisk.AZURE_PersistentDisk_name }}
    volumeAttributes:
      fsType: ext4
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pv-claim
  labels:
    app: {{ template "osm-seed.name" . }}
    component: db-pd
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
# {{- if eq .Values.cloudProvider "azure" }}
#   annotations:
#     volume.beta.kubernetes.io/storage-class: ""
# {{- end }}
spec:
  ############## Minikube ##############
  {{- if eq .Values.cloudProvider "minikube" }}
  storageClassName: local-storage
  {{- else }}
  ############## Other providers ##############
  storageClassName: ""
  {{- end }}
  volumeName: {{ .Release.Name }}-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      ############## Minikube ##############
      {{- if eq .Values.cloudProvider "minikube" }}
      storage: {{ .Values.db.persistenceDisk.localVolumeSize }}
      {{- end }}

      ############## AWS Provider ##############
      {{- if eq .Values.cloudProvider "aws" }}
      storage: {{ .Values.db.persistenceDisk.AWS_ElasticBlockStore_size }}
      {{- end }}

      ############## GCP Provider ##############
      {{- if eq .Values.cloudProvider "gcp" }}
      storage: {{ .Values.db.persistenceDisk.GCP_gcePersistentDisk_size }}
      {{- end }}

      ############## AZURE Provider ##############
      {{- if eq .Values.cloudProvider "azure" }}
      storage: {{ .Values.db.persistenceDisk.AZURE_PersistentDisk_size }}
      {{- end }}
{{- end }}
{{- end }}
