{{- if .Values.web.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "osm-seed.fullname" . }}-web
  labels:
    app: {{ template "osm-seed.name" . }}
    component: web-service
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/proxy-body-size: "300m"
    cert-manager.io/cluster-issuer: letsencrypt-prod-issuer
spec:
  {{- if eq .Values.cloudProvider "minikube" }}
  type: NodePort
  {{- else }}
  type: ClusterIP
  {{- end }}
  ports:
    - port: 80
      targetPort: http
      nodePort: null
      protocol: TCP
      name: http
  selector:
    app: {{ template "osm-seed.name" . }}
    release: {{ .Release.Name }}
    run: {{ .Release.Name }}-web
{{- end }}